### PR TITLE
Update IC commit

### PR DESCRIPTION
**Pull request by sa-github-api**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Review by lmuntaner — COMMENTED** [review]
@bitdivine @dskloetd should we add you two as reviewers of this workflow instead of all gix team?

As we agreed, each workflow should have two maintainers.

**Comment by dskloetd** [comment]
Sure. Can we also make it less frequent? I feel like I'm getting this multiple times a week. Once every 2 weeks should be enough, right?
Maybe if it's triggered by pressing a button, it only needs to go to the person who pressed the button?

**Comment by lmuntaner** [comment]
> Sure. Can we also make it less frequent? I feel like I'm getting this multiple times a week. Once every 2 weeks should be enough, right? Maybe if it's triggered by pressing a button, it only needs to go to the person who pressed the button?

Both suggestions make a lot of sense to me. Even once a week should be enough as long as it can be triggered manually also.

And yes, I think that when triggered manually it should ask the review of who pressed it.

I created a ticket for it: https://dfinity.atlassian.net/browse/GIX-2034

**Comment by dskloetd** [comment]
> > Once every 2 weeks should be enough, right?

> Even once a week should be enough

???

**Comment by lmuntaner** [comment]
> > > Once every 2 weeks should be enough, right?
> 
> > Even once a week should be enough
> 
> ???

Oops, I read twice per week. Yes, also.

**Review by bitdivine — APPROVED** [review]

**Comment by bitdivine** [comment]
I actually like the 1-per week schedule.  Occasionally it's not frequent enough, e.g. last week I had to trigger this manually to get additional runs, but most of the time I find that the frequency coinciding with our release schedule is a good thing.

**Comment by bitdivine** [comment]
It might be worth having some discussions about expected frequency of updates.  I think it would be nice to be able to say things such as:

> If an NNS API is updated, the change will be in the next release candidate (unless there are complications, in which case it may take longer).

This means that from an NNS API update, such as a new proposal type or change in proposal type, it will normally take no more than 11 days for an NNS update to be reflected in the deployed nns-dapp, assuming the change is made upstream on Wednesday and just misses the cut-off, so the change goes in production two Mondays later.

How up-to-date do our dependencies, such as proposal rendering, need to be?

**Pull request merged**
