### PR TITLE
Update IC commit

### PR DESCRIPTION
**Pull request by sa-github-api**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Review by lmuntaner — APPROVED** [review]

**Comment by lmuntaner** [comment]
@dskloetd why isn't the last one running? Is it always like this?

**Comment by dskloetd** [comment]
Last what? The bot won't press the merge button so you can just click "Squash and merge" yourself now.
I would do it but there seems to be some confusion so I'll leave it to you. @lmuntaner

**Comment by lmuntaner** [comment]
> Last what? The bot won't press the merge button so you can just click "Squash and merge" yourself now. I would do it but there seems to be some confusion so I'll leave it to you. @lmuntaner

I couldn't press the button before because one test was still pending for a long time. I see now that all is good, weird.

**Comment by dskloetd** [comment]
But if the tests are still running then there is an "Enable auto merge" button, right?

**Comment by lmuntaner** [comment]
> But if the tests are still running then there is an "Enable auto merge" button, right?

Yes, but there was a test that had been "running" forever. I didn't enable the auto-merge. It's ok, Maybe it was a temporary issue in the pipeline.

**Pull request merged**
