### PR TITLE
update-sns-aggregator

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Use latest SNS Aggregator with new fields in snapshot.

## Changes

* Change the `SNS_AGGREGATOR_RELEASE` in `versions.bash`.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* main
  * **PR #261** <a href="https://app.graphite.dev/github/pr/dfinity/snsdemo/261" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/snsdemo/261?utm_source=stack-comment).

**Review by bitdivine — APPROVED** [review]
Is this something that should be kept up to date?  If so, this can be automated.

**Comment by lmuntaner** [comment]
> Is this something that should be kept up to date? If so, this can be automated.

Yes, I believe so.

Issue: https://dfinity.atlassian.net/browse/GIX-2044 and added to the Epic on automating the IC deps.

**Review by dskloetd — APPROVED** [review]

**Comment by bitdivine** [comment]
TODO to merge:
- [ ] binstall installer action https://github.com/dfinity/snsdemo/pull/264
- [ ] Install ic-wasm (with binstall, small enough that it can be combined with:)
- [ ] Replace wasm-nm with ic-admin https://github.com/dfinity/snsdemo/pull/263

**Comment by lmuntaner** [comment]
> TODO to merge:
> 
> * [ ]  binstall installer action [feat: Installer action for binstall #264](https://github.com/dfinity/snsdemo/pull/264)
> * [ ]  Install ic-wasm (with binstall, small enough that it can be combined with:)
> * [ ]  Replace wasm-nm with ic-admin [No wasm nm #263](https://github.com/dfinity/snsdemo/pull/263)

Thanks!

**Pull request merged**
