### PR TITLE
Chore: upgrade IC commit

### PR DESCRIPTION
**Pull request by lmuntaner**
Upgrading IC Commit.

Checking why #244 is stuck.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Not needed

**Comment by dskloetd** [comment]
Please don't ignore things like that. Because then when you are on vacation, we get stuck with it: https://dfinity.slack.com/archives/CL7Q2RXUM/p1697014801586649

**Comment by bitdivine** [comment]
Believe me, they are not ignored.

**Comment by dskloetd** [comment]
In that case, please update us about what's being done about the cla issue.

**Pull request closed without merging**
